# Generated by Django 3.2 on 2021-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=800)),
                ('domain_shortened_domain', models.CharField(max_length=300)),
            ],
        ),
    ]
